$PROBLEM ferx #1004 anchor B -- ADVAN2 library routine: F1 at the dose AND in the scale, S2 = V/F1
$INPUT ID TIME DV MDV EVID AMT CMT
$DATA data.csv IGNORE=@

$SUBROUTINE ADVAN2 TRANS2

$PK
  CL = THETA(1)
  V  = THETA(2)
  KA = THETA(3)
  F1 = THETA(4)
  S2 = V/F1

$ERROR
  IPRED = F
  Y = IPRED*(1+EPS(1))

$THETA
  (5.0 FIX)   ; CL
  (50.0 FIX)  ; V
  (1.5 FIX)   ; KA
  (0.5 FIX)   ; F1

$OMEGA 0 FIX
$SIGMA 0.01 FIX

$ESTIMATION MAXEVAL=0 METHOD=1 INTER
$TABLE ID TIME IPRED NOPRINT ONEHEADER FILE=sdtab.tab
