$PROBLEM advan4_bolus_cmt3
$INPUT ID TIME DV AMT CMT EVID RATE SS II
$DATA dose_cmt_advan4_bolus_cmt3.csv IGNORE=@
$SUBROUTINES ADVAN4 TRANS4
$PK
  CL = 5
  V2 = 50
  Q  = 3
  V3 = 80
  KA = 1
  S2 = V2
$ERROR
  Y = F * (1 + EPS(1))
$THETA (5.0 FIX)   ; CL
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 PRINT=1 NOABORT
$TABLE ID TIME CMT PRED NOPRINT ONEHEADER FILE=dose_cmt_advan4_bolus_cmt3.tab FORMAT=,1PE17.10
