$PROBLEM advan2_bolus_cmt2
$INPUT ID TIME DV AMT CMT EVID RATE SS II
$DATA dose_cmt_advan2_bolus_cmt2.csv IGNORE=@
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = 5
  V  = 50
  KA = 1
  S2 = V
$ERROR
  Y = F * (1 + EPS(1))
$THETA (5.0 FIX)   ; CL
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 PRINT=1 NOABORT
$TABLE ID TIME CMT PRED NOPRINT ONEHEADER FILE=dose_cmt_advan2_bolus_cmt2.tab FORMAT=,1PE17.10
