$PROBLEM ferx #1587: lagged dose record before an EVID=3/4 reset, arrival after it
$DATA evid_reset_lag.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT MDV II SS RATE LAGC
$SUBROUTINES ADVAN13 TOL=12
$MODEL COMP=(DEPOT,DEFDOSE) COMP=(CENTRAL,DEFOBS)
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)
  KA = THETA(3)
  ALAG1 = LAGC
  S2 = V
$DES
  DADT(1) = -KA*A(1)
  DADT(2) = KA*A(1) - CL/V*A(2)
$ERROR
  IPRED = F
  Y     = IPRED+EPS(1)
$THETA 2.0 FIX  20.0 FIX  0.15 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID PRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=evid_reset_lag_advan13.sdtab
