$PROBLEM ferx #1587: lagged dose record before an EVID=3/4 reset, arrival after it
$DATA evid_reset_lag.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT MDV II SS RATE LAGC
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)
  KA = THETA(3)
  ALAG1 = LAGC
  S2 = V
$ERROR
  IPRED = F
  Y     = IPRED+EPS(1)
$THETA 2.0 FIX  20.0 FIX  0.15 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID PRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=evid_reset_lag.sdtab
