$PROBLEM #1722 non-IOV FOCE (no INTER) at sigma ~21%: EBE residual-variance anchor
$DATA warfarin_iov.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT=DROP RATE MDV OCC
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)*EXP(ETA(2))
  KA = THETA(3)*EXP(ETA(3))
  S2 = V
$ERROR
  IPRED = F
  Y = IPRED*(1 + EPS(1))
$THETA (0, 0.2) (0, 10) (0, 1.5)
$OMEGA 0.09 0.04 0.30
$SIGMA 0.04
$ESTIMATION METHOD=1 MAXEVAL=9999 NSIG=3 SIGL=9 POSTHOC PRINT=1 NOABORT
$TABLE ID TIME CWRES ETA1 ETA2 ETA3 NOPRINT ONEHEADER FORMAT=s1PE15.8 FILE=sdtab
