$PROBLEM SS dose x ODE-accumulated hazard (#1210) -- r4_const: EVID=4 reset+dose
$INPUT ID TIME DV EVID AMT CMT RATE MDV SS II
$DATA train4.csv IGNORE=@
$SUBROUTINES ADVAN13 TOL=9
$MODEL
  COMP=(DEPOT,DEFDOSE)
  COMP=(CENTRAL)
  COMP=(CHZ)
$PK
  CL   = THETA(1)*EXP(ETA(1))
  V    = THETA(2)
  KA   = THETA(3)
  H0   = THETA(4)
  BETA = THETA(5)
  K20  = CL/V
  TREC = 600
$DES
  CONCD   = A(2)/V
  DADT(1) = -KA*A(1)
  DADT(2) =  KA*A(1) - K20*A(2)
  GATE = 0
  IF (T.GE.TREC) GATE = 1
  DADT(3) =  GATE*H0*EXP(BETA*CONCD)
$ERROR
  CONC = A(2)/V
  HAZ  = H0*EXP(BETA*CONC)
  CHZ  = A(3)
  SUR  = EXP(-CHZ)
  IPRED = CONC
  Y = IPRED*(1.0 + EPS(1))
$THETA
  1.00 FIX
  10.0 FIX
  1.00 FIX
  0.02 FIX
  0.0 FIX
$OMEGA 0 FIX
$SIGMA 0.01
$ESTIMATION METHOD=1 LAPLACE INTER NUMERICAL SLOW MAXEVAL=0 POSTHOC PRINT=1 NOABORT
$TABLE ID TIME CMT DV EVID IPRED CHZ HAZ MDV NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE15.8 FILE=ss_chz_r4_const.tab
