$PROBLEM ferx #1586: an infusion running across a mid-timeline SS=1 record (ADVAN2)
$DATA ss_infusion_stop.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT MDV II SS RATE LAG1 LAG2
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)
  KA = THETA(3)
  ALAG1 = LAG1
  ALAG2 = LAG2
  D1 = 8
  S2 = V
$ERROR
  IPRED = F
  Y     = IPRED+EPS(1)
$THETA 2.0 FIX  20.0 FIX  0.15 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID PRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=ss_infusion_stop.sdtab
