$PROBLEM ferx #1586: an infusion running across a mid-timeline SS=1 record (ADVAN13)
$DATA ss_infusion_stop.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT MDV II SS RATE LAG1 LAG2
$SUBROUTINES ADVAN13 TOL=12
$MODEL COMP=(DEPOT,DEFDOSE) COMP=(CENTRAL,DEFOBS)
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)
  KA = THETA(3)
  ALAG1 = LAG1
  ALAG2 = LAG2
  D1 = 8
  S2 = V
$DES
  DADT(1) = -KA*A(1)
  DADT(2) = KA*A(1) - CL/V*A(2)
$ERROR
  IPRED = F
  Y     = IPRED+EPS(1)
$THETA 2.0 FIX  20.0 FIX  0.15 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID PRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=ss_infusion_stop_advan13.sdtab
