$PROBLEM ferx #1576: mid-timeline SS=1 into a transit(n=3) chain, prior regimen in flight (ADVAN13)
$DATA ss_reset_transit.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT MDV II SS
$SUBROUTINES ADVAN13 TOL=12
$MODEL
  COMP=(DEPOT,DEFDOSE)
  COMP=(TR1)
  COMP=(TR2)
  COMP=(TR3)
  COMP=(CENTRAL)
  COMP=(OBS,DEFOBS)
$PK
  CL  = THETA(1)*EXP(ETA(1))
  V   = THETA(2)
  MTT = THETA(3)
  KTR = 4/MTT
  S6  = 1
$DES
  DADT(1) = -KTR*A(1)
  DADT(2) =  KTR*A(1) - KTR*A(2)
  DADT(3) =  KTR*A(2) - KTR*A(3)
  DADT(4) =  KTR*A(3) - KTR*A(4)
  DADT(5) =  KTR*A(4) - (CL/V)*A(5)
  DADT(6) =  0
$ERROR
  IPRED = A(5)/V
  Y     = IPRED+EPS(1)
$THETA 2.0 FIX  20.0 FIX  6.0 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID IPRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=sdtab
