$PROBLEM ferx #1588: bolus row co-timed with an SS=1 row, ALAG1=0
$DATA ss_reset_tie.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT MDV II SS RATE
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)
  KA = THETA(3)
  ALAG1 = 0
  S2 = V
$ERROR
  IPRED = F
  Y     = IPRED*(1+EPS(1))
$THETA 2.0 FIX  20.0 FIX  0.15 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 NOABORT
$TABLE ID TIME EVID PRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=sdtab
