$PROBLEM ss_slow_advan1
$INPUT ID TIME DV AMT CMT EVID RATE SS II
$DATA ss_slow_advan1.csv IGNORE=@
$SUBROUTINES ADVAN1 TRANS2
$PK
  CL = 0.1
  V  = 50
  S1 = V
$ERROR
  Y = F * (1 + EPS(1))
$THETA (0.1 FIX)   ; CL
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 PRINT=1 NOABORT
$TABLE ID TIME CMT PRED NOPRINT ONEHEADER FILE=ss_slow_advan1.tab FORMAT=,1PE17.10
