$PROBLEM ferx batch-T probe: explicit 41-dose train, DES reads ABSOLUTE T
$INPUT ID TIME DV EVID AMT CMT MDV II SS
$DATA train_tabs_n21.csv IGNORE=@
$SUBROUTINES ADVAN13 TOL=9
$MODEL COMP=(CENTRAL,DEFDOSE,DEFOBS)
$PK
  CL = THETA(1)
  V  = THETA(2)
  S1 = V
$DES
  DADT(1) = -(CL/V)*A(1)*(1.0 + 0.003*T)
$ERROR
  IPRED = F
  Y = IPRED*(1 + EPS(1))
$THETA 1.0 FIX 20.0 FIX
$OMEGA 0 FIX
$SIGMA 0.01 FIX
$ESTIMATION MAXEVAL=0 METHOD=0 POSTHOC NOABORT
$TABLE ID TIME EVID PRED IPRED NOPRINT ONEHEADER FORMAT=,1PE20.13 FILE=train_tabs_n21.tab
