$PROBLEM Warfarin 1cpt oral FOCE (no INTER) - ferx #1710 CWRES oracle
$DATA warfarin_foce_cwres.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT=DROP RATE MDV
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)*EXP(ETA(2))
  KA = THETA(3)*EXP(ETA(3))
  S2 = V
$ERROR
  IPRED = F
  Y = IPRED*(1 + EPS(1))
$THETA (0, 0.2) (0, 10.0) (0, 1.5)
$OMEGA 0.09 0.04 0.30
$SIGMA 0.0004
$ESTIMATION METHOD=1 MAXEVAL=9999 NSIG=3 SIGL=9 PRINT=5 NOABORT POSTHOC FORMAT=s1PE23.16
$TABLE ID TIME EVID CWRES PRED NOPRINT ONEHEADER NOAPPEND FORMAT=s1PE23.16 FILE=warfarin_foce_cwres.tab
