; Joint PK-TTE (ODE-accumulated hazard) — NONMEM reference for ferx Slice 2.1 (#564).
;
; Mirrors examples/pktte_joint.ferx: oral 1-cpt PK (concentration observed on CMT 2) +
; a drug-driven hazard h = H0*exp(BETA*Cc) accumulated in a cumulative-hazard compartment
; (CMT 3), fitted jointly with the PK by the conditional Laplacian method. This is the
; standard NONMEM $DES + cumulative-hazard + F_FLAG joint construct (Holford 2013).
;
; Data: pktte_joint.csv (generated by simulate.R; CMT 1 dose, CMT 2 PK conc, CMT 3 event).
; Run:  nmfe75 nonmem.ctl nonmem.lst   ->   paste theta/omega/OFV into expected.md
;
; Truth used to simulate: CL=1, V=10, KA=1, H0=0.015, BETA=0.25, omega(CL)=0.09,
; proportional PK error sd=0.10, dose=100, horizon=24 (≈35% right-censored).

$PROBLEM  Joint PK-TTE — ODE-accumulated hazard (ferx anchor #564)

$INPUT    ID TIME DV EVID AMT CMT MDV
$DATA     pktte_joint.csv IGNORE=@

$SUBROUTINES ADVAN13 TOL=9
$MODEL
  COMP=(DEPOT,DEFDOSE)
  COMP=(CENTRAL)
  COMP=(CUMHAZ)

$PK
  CL   = THETA(1)*EXP(ETA(1))
  V    = THETA(2)
  KA   = THETA(3)
  H0   = THETA(4)
  BETA = THETA(5)
  KE   = CL/V

$DES
  CONC    = A(2)/V
  DADT(1) = -KA*A(1)
  DADT(2) =  KA*A(1) - KE*A(2)
  DADT(3) =  H0*EXP(BETA*CONC)          ; cumulative hazard accumulator (= ferx __chz)

$ERROR
  CONC = A(2)/V
  CHZ  = A(3)
  HAZ  = H0*EXP(BETA*CONC)
  IF (CMT.EQ.2) THEN                    ; Gaussian PK observation (concentration)
    F_FLAG = 0
    Y = CONC*(1 + ERR(1))
  ELSE                                  ; TTE observation on CMT 3 (F_FLAG=1 => Y is L)
    F_FLAG = 1
    IF (DV.EQ.1) Y = HAZ*EXP(-CHZ)      ; exact event:    h(T)*S(T)
    IF (DV.EQ.0) Y = EXP(-CHZ)          ; right-censored: S(T)
  ENDIF

$THETA
  (0,  1.0)     ; 1 CL
  (0, 10.0)     ; 2 V
  (0,  1.0)     ; 3 KA
  (0,  0.015)   ; 4 H0
  0.25          ; 5 BETA
$OMEGA
  0.09          ; ETA(1) on CL
$SIGMA
  0.01          ; proportional PK error variance (sd ~ 0.1)

; LAPLACIAN + INTERACTION are required for the F_FLAG=1 (likelihood) TTE rows.
$ESTIMATION METHOD=COND LAPLACE INTER MAXEVAL=9999 PRINT=5 NOABORT
$COVARIANCE
$TABLE ID TIME CMT DV PRED NOPRINT ONEHEADER FILE=pktte_joint.tab
