//! NONMEM FOCEI cross-check for **analytic transit absorption under IOV** (#719), and the
//! regression guard on the inner-EBE convergence fix that closed the ~8-unit gap #810 tracked.
//!
//! ferx's `pk one_cpt_transit(cl, v, n, mtt)` with inter-occasion variability on CL routes each
//! subject to its `transit()` ODE twin — the exponential-tilting closed-form superposition
//! cannot carry a dose's drug across an occasion boundary (#104), so IOV is served by the twin,
//! which integrates the cross-occasion carryover exactly (#486/#663). This test pins ferx's
//! FOCEI IOV objective — and its per-subject EBEs / objective contributions — on that path to
//! NONMEM.
//!
//! Data `nonmem_anchor/transit_iov.csv` (24 subjects × 3 occasions, one dose per occasion with
//! near-complete washout, observations in the informative range) was generated by
//! `tests/gen_transit_iov_anchor.rs`. NONMEM control `nonmem_anchor/transit_iov.ctl` is an
//! `ADVAN13 TOL=9` `$DES` Savic transit density delivered as `R_in` into a single central
//! compartment (matching `one_cpt_transit`, which is transit-into-central), with IOV on CL as one
//! ETA per occasion sharing one variance (`$OMEGA BLOCK SAME`) and BSV on V — a well-identified,
//! no-ω-collapse design. NONMEM 7.6.0 FOCEI: #OBJV = -1374.269 at THETA = (9.2367, 27.920,
//! 0.9951, 2.9893), ω²(BSV V) = 0.114001, ω²(IOV CL) = 0.060242, σ² = 0.010481.
//!
//! Because `one_cpt_transit`'s single disposition compartment *is* CMT 1, ferx reads the very
//! same csv NONMEM does (no depot/central re-keying). ODE tolerances are pinned to 1e-9 to
//! mirror NONMEM's `TOL=9`.
//!
//! **Result:** ferx's transit+IOV OFV matches #OBJV to ~0.016, and its per-subject BSV-V EBEs and
//! objective contributions match NONMEM's `.phi` — the ODE-path IOV FOCEI objective sits in the
//! same tight band as the analytic-IOV (`warfarin_iov_nonmem.rs`, ~0.6) and non-IOV ODE
//! (`igd`/`weibull`, ~0.01) anchors.
//!
//! **History (#810/#814) — why this anchor exists and what the earlier ~8-unit gap was NOT.** An
//! earlier state of this test sat ~8.25 OFV units high, and #810 hypothesised the cause was FD of
//! the κ (IOV) columns of the augmented Laplace `H` through the RK45 twin's occasion-boundary CL
//! discontinuity in `foce_subject_nll_iov`. That hypothesis was wrong. The gap was **under-
//! converged inner EBEs on the twin-rerouted subjects** (#814 §2): the inner objective-stall
//! convergence stop (#555) was gated on `model.ode_spec.is_some()`, which is `false` for the
//! analytic transit/IG *primary*, so every subject rerouted to the ODE twin ran with the stall
//! stop disabled and could return to `MAX_INNER` under-converged — inflating the marginal it
//! feeds. #816 re-gated the stop on the *effective* (twin) model (`effective_for`), collapsing the
//! gap 8.25 → 0.016 with **no change to the marginal**: `foce_subject_nll_iov` and its FD κ
//! columns are byte-identical across the fix, and the analytic-IOV warfarin anchor (which shares
//! that marginal code, FD κ columns and all) was always tight — proving the FD κ columns were
//! never the cause. The bug was specific to the transit/IG twin reroute; a hand-written `[odes]`
//! + IOV model has `ode_spec = Some`, so its stall stop was always enabled and it was unaffected.
//! The per-subject `.phi` checks below lock the EBE convergence directly (a regression to the
//! disabled-stall state re-inflates them), and the tight OFV band guards the aggregate.

use ferx_core::parser::model_parser::parse_model_string;
use ferx_core::{fit, read_nonmem_csv, EstimationMethod, FitOptions};
use std::collections::HashMap;
use std::path::Path;

const NM_TVCL: f64 = 9.23666;
const NM_TVV: f64 = 27.9198;
const NM_TVMTT: f64 = 0.995111;
const NM_TVN: f64 = 2.98930;
const NM_OMEGA_V: f64 = 0.114001;
const NM_OMEGA_IOV: f64 = 0.0602419;
const NM_SIGMA_PROP_SD: f64 = 0.102374; // sqrt(0.0104806)
const NM_OFV_NO_CONST: f64 = -1374.269;

/// Per-subject NONMEM EBE (BSV-V mode) and objective contribution parsed from the committed
/// `.phi`. Columns (whitespace-delimited, two header lines): `SUBJECT_NO ID ETA(1..4)
/// ETC(1,1..4,4) OBJ`. `ETA(1)` is BSV on V (the only random effect ferx surfaces per subject —
/// the IOV κ are population-level), and the final `OBJ` column is the per-subject objective, which
/// sums to NONMEM's #OBJV-without-constant (verified: Σ OBJ = -1374.2692), the same convention as
/// ferx's `SubjectResult::ofv_contribution`.
fn nonmem_phi_per_subject(path: &Path) -> HashMap<String, (f64, f64)> {
    let text = std::fs::read_to_string(path).expect("transit_iov .phi loads");
    let mut out = HashMap::new();
    for line in text.lines().skip(2) {
        let f: Vec<&str> = line.split_whitespace().collect();
        if f.len() < 3 {
            continue;
        }
        let id = f[1].to_string();
        let eta1: f64 = f[2].parse().expect("phi ETA(1) parses");
        let obj: f64 = f[f.len() - 1].parse().expect("phi OBJ parses");
        out.insert(id, (eta1, obj));
    }
    out
}

#[test]
#[cfg_attr(
    not(feature = "slow-tests"),
    ignore = "slow: NONMEM transit+IOV anchor, opt in with --features slow-tests"
)]
fn transit_iov_objective_matches_nonmem() {
    // `pk one_cpt_transit` + IOV on CL, all parameters FIXed at NONMEM's MLE. omega/kappa are
    // variances; sigma is the SD ferx reports.
    let fixed = format!(
        r"
[parameters]
  theta TVCL({NM_TVCL}, FIX)
  theta TVV({NM_TVV}, FIX)
  theta TVMTT({NM_TVMTT}, FIX)
  theta TVN({NM_TVN}, FIX)
  omega ETA_V  ~ {NM_OMEGA_V} FIX
  kappa KAPPA_CL ~ {NM_OMEGA_IOV} FIX
  sigma PROP_ERR ~ {prop} (sd) FIX

[individual_parameters]
  CL  = TVCL * exp(KAPPA_CL)
  V   = TVV  * exp(ETA_V)
  MTT = TVMTT
  NTR = TVN

[structural_model]
  pk one_cpt_transit(cl=CL, v=V, n=NTR, mtt=MTT)

[error_model]
  DV ~ proportional(PROP_ERR)

[fit_options]
  method     = focei
  iov_column = OCC
  ode_reltol = 1e-9
  ode_abstol = 1e-9
",
        prop = NM_SIGMA_PROP_SD,
    );

    let model = parse_model_string(&fixed).expect("fixed-param transit IOV model parses");
    let pop = read_nonmem_csv(
        Path::new("nonmem_anchor/transit_iov.csv"),
        None,
        Some("OCC"),
    )
    .expect("transit_iov anchor data loads");

    let mut opts = FitOptions::default();
    opts.method = EstimationMethod::FoceI;
    opts.interaction = true; // match NONMEM METHOD=1 INTER
    opts.run_covariance_step = false;
    opts.ode_reltol = 1e-9; // match NONMEM ADVAN13 TOL=9
    opts.ode_abstol = 1e-9;
    opts.inner_tol = 1e-6;
    opts.verbose = false;

    let result = fit(&model, &pop, &model.default_params, &opts)
        .expect("fixed-param transit IOV objective evaluation must run");

    let diff = (NM_OFV_NO_CONST - result.ofv).abs();
    println!(
        "FERX transit+IOV @ NONMEM optimum = {:.4}; NONMEM #OBJV = {:.4}; |gap| = {:.4}",
        result.ofv, NM_OFV_NO_CONST, diff
    );
    // Agreement tolerance (NOT a regression band on a known gap): ferx's ODE-path IOV FOCEI
    // objective now matches #OBJV to ~0.016, the same band as the analytic-IOV and non-IOV-ODE
    // anchors. A regression to the pre-#816 disabled-inner-stall state re-inflates this to ~8.25
    // and trips the assertion — the guard the loose pre-fix `< 12` band could never provide. See
    // the module docs for the #810/#814 history.
    assert!(
        result.ofv.is_finite() && diff < 1.0,
        "ferx FOCEI transit+IOV at NONMEM's optimum = {:.4}; NONMEM #OBJV = {:.4}; |gap| {:.4} \
         exceeds the 1-OFV agreement tolerance — regression toward the pre-#816 under-converged \
         inner-EBE gap (~8.25) on the twin-rerouted IOV subjects (#810/#814)",
        result.ofv,
        NM_OFV_NO_CONST,
        diff
    );

    // Per-subject EBE / objective agreement against NONMEM's `.phi` — the *direct* lock on the
    // inner-EBE convergence that closed #810. If the inner stall stop were disabled again for the
    // rerouted subjects, their EBEs would drift and their objective contributions would inflate,
    // even though the aggregate could partly cancel; asserting per subject catches that locally.
    let phi = nonmem_phi_per_subject(Path::new("nonmem_anchor/results/transit_iov.phi"));
    assert_eq!(
        result.subjects.len(),
        phi.len(),
        "subject count mismatch: ferx {} vs .phi {}",
        result.subjects.len(),
        phi.len()
    );
    let mut max_eta_dev = 0.0_f64;
    let mut max_obj_dev = 0.0_f64;
    for subj in &result.subjects {
        let (nm_eta1, nm_obj) = phi
            .get(&subj.id)
            .unwrap_or_else(|| panic!("subject {} missing from .phi", subj.id));
        let eta_dev = (subj.eta[0] - nm_eta1).abs();
        let obj_dev = (subj.ofv_contribution - nm_obj).abs();
        max_eta_dev = max_eta_dev.max(eta_dev);
        max_obj_dev = max_obj_dev.max(obj_dev);
    }
    println!(
        "FERX vs NONMEM .phi: max |Δ BSV-V EBE| = {max_eta_dev:.5}; max |Δ per-subject OBJ| = {max_obj_dev:.5}"
    );
    // Observed on the fix (main): max |Δ EBE| ≈ 3e-5, max |Δ OBJ| ≈ 0.012. The bands below keep
    // ample margin over that yet sit well inside the regression signal — the pre-#816
    // disabled-stall state inflates the objective by ~8.25 over 24 subjects (~0.34/subject), so a
    // reappearance drives max |Δ OBJ| past 0.2 and the EBEs well past 0.01.
    assert!(
        max_eta_dev < 0.01,
        "per-subject BSV-V EBE drifts from NONMEM .phi by up to {max_eta_dev:.5} — inner-EBE \
         under-convergence regression on the twin-rerouted subjects (#810/#814)"
    );
    assert!(
        max_obj_dev < 0.2,
        "per-subject objective contribution drifts from NONMEM .phi by up to {max_obj_dev:.5} — \
         inner-EBE under-convergence regression on the twin-rerouted subjects (#810/#814)"
    );
}
