//! NONMEM FOCEI cross-check for **analytic transit absorption under IOV** (#719).
//!
//! ferx's `pk one_cpt_transit(cl, v, n, mtt)` with inter-occasion variability on CL routes each
//! subject to its `transit()` ODE twin — the exponential-tilting closed-form superposition
//! cannot carry a dose's drug across an occasion boundary (#104), so IOV is served by the twin,
//! which integrates the cross-occasion carryover exactly (#486/#663). This test pins ferx's
//! FOCEI IOV objective on that path to NONMEM.
//!
//! Data `nonmem_anchor/transit_iov.csv` (24 subjects × 3 occasions, one dose per occasion with
//! near-complete washout, observations in the informative range) was generated by
//! `tests/gen_transit_iov_anchor.rs`. NONMEM control `nonmem_anchor/transit_iov.ctl` is an
//! `ADVAN13 TOL=9` `$DES` Savic transit density delivered as `R_in` into a single central
//! compartment (matching `one_cpt_transit`, which is transit-into-central), with IOV on CL as one
//! ETA per occasion sharing one variance (`$OMEGA BLOCK SAME`) and BSV on V — a well-identified,
//! no-ω-collapse design. NONMEM 7.6.0 FOCEI: #OBJV = -1374.269 at THETA = (9.2367, 27.920,
//! 0.9951, 2.9893), ω²(BSV V) = 0.114001, ω²(IOV CL) = 0.060242, σ² = 0.010481.
//!
//! Because `one_cpt_transit`'s single disposition compartment *is* CMT 1, ferx reads the very
//! same csv NONMEM does (no depot/central re-keying). ODE tolerances are pinned to 1e-9 to
//! mirror NONMEM's `TOL=9`.
//!
//! **Result / finding:** ferx's transit+IOV OFV at NONMEM's optimum is ≈ 8 units off #OBJV — and
//! that gap is **not** the #719 reroute. The reroute is exact (predictions match the hand-written
//! `transit()` forcing bit-for-bit at κ≠0, `transit_analytic_equivalence.rs`); the gap is a
//! pre-existing difference in ferx's **ODE-path IOV FOCEI *objective marginal* vs NONMEM**
//! (analytical IOV matches to ~0.6, `warfarin_iov_nonmem.rs`) — orthogonal to #719, shared by
//! every ODE+IOV model, and first measured here. The assertion body records the ruled-out causes
//! and the fix direction; tracked in #810.

use ferx_core::parser::model_parser::parse_model_string;
use ferx_core::{fit, read_nonmem_csv, EstimationMethod, FitOptions};
use std::path::Path;

const NM_TVCL: f64 = 9.23666;
const NM_TVV: f64 = 27.9198;
const NM_TVMTT: f64 = 0.995111;
const NM_TVN: f64 = 2.98930;
const NM_OMEGA_V: f64 = 0.114001;
const NM_OMEGA_IOV: f64 = 0.0602419;
const NM_SIGMA_PROP_SD: f64 = 0.102374; // sqrt(0.0104806)
const NM_OFV_NO_CONST: f64 = -1374.269;

#[test]
#[cfg_attr(
    not(feature = "slow-tests"),
    ignore = "slow: NONMEM transit+IOV anchor, opt in with --features slow-tests"
)]
fn transit_iov_objective_matches_nonmem() {
    // `pk one_cpt_transit` + IOV on CL, all parameters FIXed at NONMEM's MLE. omega/kappa are
    // variances; sigma is the SD ferx reports.
    let fixed = format!(
        r"
[parameters]
  theta TVCL({NM_TVCL}, FIX)
  theta TVV({NM_TVV}, FIX)
  theta TVMTT({NM_TVMTT}, FIX)
  theta TVN({NM_TVN}, FIX)
  omega ETA_V  ~ {NM_OMEGA_V} FIX
  kappa KAPPA_CL ~ {NM_OMEGA_IOV} FIX
  sigma PROP_ERR ~ {prop} (sd) FIX

[individual_parameters]
  CL  = TVCL * exp(KAPPA_CL)
  V   = TVV  * exp(ETA_V)
  MTT = TVMTT
  NTR = TVN

[structural_model]
  pk one_cpt_transit(cl=CL, v=V, n=NTR, mtt=MTT)

[error_model]
  DV ~ proportional(PROP_ERR)

[fit_options]
  method     = focei
  iov_column = OCC
  ode_reltol = 1e-9
  ode_abstol = 1e-9
",
        prop = NM_SIGMA_PROP_SD,
    );

    let model = parse_model_string(&fixed).expect("fixed-param transit IOV model parses");
    let pop = read_nonmem_csv(
        Path::new("nonmem_anchor/transit_iov.csv"),
        None,
        Some("OCC"),
    )
    .expect("transit_iov anchor data loads");

    let mut opts = FitOptions::default();
    opts.method = EstimationMethod::FoceI;
    opts.interaction = true; // match NONMEM METHOD=1 INTER
    opts.run_covariance_step = false;
    opts.ode_reltol = 1e-9; // match NONMEM ADVAN13 TOL=9
    opts.ode_abstol = 1e-9;
    opts.inner_tol = 1e-6;
    opts.verbose = false;

    let result = fit(&model, &pop, &model.default_params, &opts)
        .expect("fixed-param transit IOV objective evaluation must run");

    let diff = (NM_OFV_NO_CONST - result.ofv).abs();
    println!(
        "FERX transit+IOV @ NONMEM optimum = {:.4}; NONMEM #OBJV = {:.4}; |gap| = {:.4}",
        result.ofv, NM_OFV_NO_CONST, diff
    );
    // FINDING (this anchor's real result): |gap| ≈ 8 OFV units — and it is NOT the #719 reroute.
    // The transit+IOV *predictions* are exact: they match the hand-written `transit()` ODE forcing
    // model bit-for-bit at non-zero per-occasion κ (`transit_analytic_equivalence.rs`
    // `transit_iov_matches_hand_written_ode_forcing`). The gap is a **pre-existing difference in
    // ferx's ODE-path IOV FOCEI *objective* marginal vs NONMEM**, orthogonal to #719 and shared by
    // every ODE+IOV model (a hand-written `[odes]` + IOV too). It is ruled *out* as: the reroute
    // (predictions exact), a near-boundary ω (a clean, well-identified BSV-V/IOV-CL design still
    // gives 8.25), and ODE tolerances (1e-9 gives ~8). Two tight anchors bracket the cause:
    // analytical IOV matches NONMEM to ~0.6 (`warfarin_iov_nonmem.rs`) and *non-IOV* ODE matches to
    // ~0.01 (`igd`/`weibull` at optimum) — and BOTH already finite-difference their Laplace `H`
    // (`compute_jacobian_fd`), so "FD `H`" per se is not the differentiator. `foce_subject_nll_iov`
    // is the *same* function in the warfarin (0.6) and transit (8) cases; the ONLY difference is the
    // prediction engine (analytic vs the RK45 twin). The sharpest remaining candidate is therefore
    // what the ODE+IOV combination uniquely does: FD a κ element that step-switches an occasion's CL
    // at the occasion boundary and propagates through the RK45 into every later occasion (a dense
    // `H` column crossing `dA/dt` discontinuities) — neither analytic-IOV nor non-IOV-ODE FDs
    // *through* an occasion-boundary CL step in an adaptive integrator. An EBE difference at κ≠0 from
    // the same effect in the inner loop is the alternative; #810 records the isolate-then-fix plan
    // (compare EBEs/preds to NONMEM `.phi`, then feed `H` from the analytic ODE-IOV sensitivities
    // already used for the gradient). The band below is a **regression guard on that known gap** (a
    // reroute regression would balloon it), NOT an agreement tolerance; tighten to < 1 once fixed.
    assert!(
        result.ofv.is_finite() && diff < 12.0,
        "ferx FOCEI transit+IOV at NONMEM's optimum = {:.4}; NONMEM #OBJV = {:.4}; |gap| {:.4} \
         exceeds the ODE-IOV-marginal regression band (12 OFV units) — a reroute regression or a \
         further marginal drift beyond the known ~8-unit ODE-IOV objective-marginal gap",
        result.ofv,
        NM_OFV_NO_CONST,
        diff
    );
}
