$PROBLEM 1-cpt oral, three occasions, simulated IOV on CL only - IIV-only input for iovsearch (ferx-core #1183)
$DATA iov_sim.csv IGNORE=@
$INPUT ID TIME DV EVID AMT CMT=DROP RATE MDV OCC
$SUBROUTINES ADVAN2 TRANS2
$PK
  CL = THETA(1)*EXP(ETA(1))
  V  = THETA(2)*EXP(ETA(2))
  KA = THETA(3)*EXP(ETA(3))
  S2 = V
$ERROR
  IPRED = F
  Y = IPRED + IPRED*EPS(1)
$THETA (0, 0.5)    ; TVCL
$THETA (0, 10.0)   ; TVV
$THETA (0, 1.2)    ; TVKA
$OMEGA 0.09        ; ETA_CL
$OMEGA 0.04        ; ETA_V
$OMEGA 0.30        ; ETA_KA
$SIGMA 0.04        ; sigma^2 (SD 0.2)
$ESTIMATION METHOD=COND INTERACTION MAXEVAL=9999 PRINT=5 NOABORT
$TABLE ID TIME DV MDV IPRED CWRES NOPRINT ONEHEADER FILE=sdtab
