use super::*;
use std::collections::HashMap;

/// Build an analytical-PK model (`tv_fn = Some`, `ode_spec = None`).
pub(crate) fn analytical_model(gradient_method: GradientMethod) -> CompiledModel {
    make_compiled_model(false, gradient_method)
}

/// Build an ODE-backed model (`tv_fn = None`, `ode_spec = Some`).
pub(crate) fn ode_model(gradient_method: GradientMethod) -> CompiledModel {
    make_compiled_model(true, gradient_method)
}

fn make_compiled_model(with_ode: bool, gradient_method: GradientMethod) -> CompiledModel {
    CompiledModel {
        covariate_model: None,
        name: "test".into(),
        pk_model: PkModel::OneCptOral,
        error_model: ErrorModel::Additive,
        error_spec: ErrorSpec::Single(ErrorModel::Additive),
        residual_correlations: Vec::new(),
        pk_param_fn: Box::new(|_, _, _, _| PkParams::default()),
        n_theta: 1,
        n_eta: 1,
        n_epsilon: 1,
        n_kappa: 0,
        theta_names: vec!["CL".into()],
        eta_names: vec!["ETA_CL".into()],
        kappa_names: Vec::new(),
        indiv_param_names: vec!["CL".into()],
        indiv_param_partials: IndivParamPartials::empty(),
        default_params: ModelParameters {
            residual_correlations: Vec::new(),
            residual_correlation_fixed: Vec::new(),
            theta: vec![1.0],
            theta_names: vec!["CL".into()],
            theta_lower: vec![0.0],
            theta_upper: vec![f64::INFINITY],
            theta_fixed: vec![false],
            omega: OmegaMatrix::from_diagonal(&[0.1], vec!["ETA_CL".into()]),
            omega_fixed: vec![false],
            sigma: SigmaVector {
                values: vec![0.1],
                names: vec!["EPS".into()],
            },
            sigma_fixed: vec![false],
            omega_iov: None,
            kappa_fixed: Vec::new(),
            mixture: None,
        },
        omega_init_as_sd: vec![false],
        sigma_init_as_sd: vec![false],
        kappa_init_as_sd: Vec::new(),
        kappa_weights: Vec::new(),
        mu_refs: HashMap::new(),
        kappa_mu_refs: HashMap::new(),
        // Analytical models populate tv_fn; ODE models leave it None.
        tv_fn: if with_ode {
            None
        } else {
            Some(Box::new(|_t, _c| vec![1.0]))
        },
        pk_indices: vec![],
        eta_map: vec![],
        pk_idx_f64: vec![],
        sel_flat: vec![],
        diffusion_theta_start: None,
        diffusion_state_indices: Vec::new(),
        ode_spec: if with_ode {
            Some(crate::ode::OdeSpec {
                chz_state_slots: Vec::new(),
                rhs: Box::new(|_y, _p, _t, _dy| {}),
                n_states: 2,
                state_names: vec!["depot".into(), "central".into()],
                readout: crate::ode::OdeReadout::ObsCmt(0),
                diffusion_var: Vec::new(),
                init_fn: None,
                solver_opts: crate::ode::OdeSolverOptions::default(),
                input_rate: Vec::new(),
                rhs_program: None,
                readout_program: None,
                indiv_param_program: None,
                dose_attr_map: Default::default(),
            })
        } else {
            None
        },
        dose_attr_map: Default::default(),
        bloq_method: BloqMethod::Drop,
        referenced_covariates: vec![],
        gradient_method,
        parse_warnings: Vec::new(),
        has_conditional_eta_params: false,
        eta_param_info: Vec::new(),
        theta_transform: Vec::new(),
        theta_eta_linked: Vec::new(),
        #[cfg(feature = "nn")]
        covariate_nns: Vec::new(),
        scaling: ScalingSpec::None,
        log_transform: false,
        dv_pre_logged: false,
        derived_exprs: vec![],
        output_columns: vec![],
        #[cfg(feature = "survival")]
        endpoints: HashMap::new(),
        frem_config: None,
        residual_error_eta: None,
        analytical_init: Vec::new(),
        analytic_readout: None,
        ruv_magnitude: None,
        absorption_ode_equivalent: None,
        mixture: None,
    }
}

/// A 1-cpt IV model with **proportional** error whose CL scales with the
/// `WT` covariate (`CL = TVCL·WT/70`), paired with a subject whose `WT`
/// rises across observation rows (70 → 140 → 210). Because `WT` is
/// time-varying, the TV-aware predictor and the baseline-only
/// `pk_param_fn(subject.covariates)` disagree on every obs row after the
/// first — the fixture shared by the simulation / NPDE / NCA-sweep
/// TV-covariate regression tests (#506). `n_eta = 0` so the only spread in
/// simulated replicates is residual error, which keeps NPD deterministic.
pub(crate) fn tv_cov_iv_model_and_subject() -> (CompiledModel, Subject) {
    let params = ModelParameters {
        residual_correlations: Vec::new(),
        residual_correlation_fixed: Vec::new(),
        theta: vec![5.0, 50.0],
        theta_names: vec!["TVCL".into(), "TVV".into()],
        theta_lower: vec![0.1, 5.0],
        theta_upper: vec![50.0, 500.0],
        theta_fixed: vec![false; 2],
        omega: OmegaMatrix::from_diagonal(&[], vec![]),
        omega_fixed: Vec::new(),
        sigma: SigmaVector {
            values: vec![0.05],
            names: vec!["PROP_ERR".into()],
        },
        sigma_fixed: vec![false],
        omega_iov: None,
        kappa_fixed: Vec::new(),
        mixture: None,
    };
    let model = CompiledModel {
        covariate_model: None,
        name: "tv_cov_iv".into(),
        pk_model: PkModel::OneCptIv,
        error_model: ErrorModel::Proportional,
        error_spec: ErrorSpec::Single(ErrorModel::Proportional),
        residual_correlations: Vec::new(),
        pk_param_fn: Box::new(
            |theta: &[f64], _eta: &[f64], cov: &HashMap<String, f64>, _t: f64| {
                let mut p = PkParams::default();
                let wt = cov.get("WT").copied().unwrap_or(70.0);
                p.values[0] = theta[0] * (wt / 70.0);
                p.values[1] = theta[1];
                p
            },
        ),
        n_theta: 2,
        n_eta: 0,
        n_epsilon: 1,
        n_kappa: 0,
        kappa_names: Vec::new(),
        theta_names: vec!["TVCL".into(), "TVV".into()],
        eta_names: Vec::new(),
        indiv_param_names: vec!["CL".into(), "V".into()],
        indiv_param_partials: IndivParamPartials::empty(),
        default_params: params.clone(),
        omega_init_as_sd: Vec::new(),
        sigma_init_as_sd: vec![false],
        kappa_init_as_sd: Vec::new(),
        kappa_weights: Vec::new(),
        mu_refs: HashMap::new(),
        kappa_mu_refs: HashMap::new(),
        tv_fn: None,
        pk_indices: vec![0, 1],
        eta_map: Vec::new(),
        pk_idx_f64: vec![0.0, 1.0],
        sel_flat: Vec::new(),
        ode_spec: None,
        dose_attr_map: Default::default(),
        diffusion_theta_start: None,
        diffusion_state_indices: Vec::new(),
        bloq_method: BloqMethod::Drop,
        referenced_covariates: vec!["WT".into()],
        gradient_method: GradientMethod::Fd,
        parse_warnings: Vec::new(),
        has_conditional_eta_params: false,
        eta_param_info: Vec::new(),
        theta_transform: Vec::new(),
        theta_eta_linked: Vec::new(),
        #[cfg(feature = "nn")]
        covariate_nns: Vec::new(),
        scaling: ScalingSpec::None,
        log_transform: false,
        dv_pre_logged: false,
        derived_exprs: vec![],
        output_columns: vec![],
        #[cfg(feature = "survival")]
        endpoints: HashMap::new(),
        frem_config: None,
        residual_error_eta: None,
        analytical_init: Vec::new(),
        analytic_readout: None,
        ruv_magnitude: None,
        absorption_ode_equivalent: None,
        mixture: None,
    };

    let mut baseline_cov = HashMap::new();
    baseline_cov.insert("WT".to_string(), 70.0);
    let subject = Subject {
        id: "TVCOV".to_string(),
        doses: vec![DoseEvent::new(0.0, 100.0, 1, 0.0, false, 0.0)],
        obs_times: vec![1.0, 2.0, 3.0],
        obs_raw_times: Vec::new(),
        observations: vec![0.0, 0.0, 0.0],
        obs_cmts: vec![1, 1, 1],
        covariates: baseline_cov,
        dose_covariates: vec![HashMap::from([("WT".to_string(), 70.0)])],
        obs_covariates: vec![
            HashMap::from([("WT".to_string(), 70.0)]),
            HashMap::from([("WT".to_string(), 140.0)]),
            HashMap::from([("WT".to_string(), 210.0)]),
        ],
        pk_only_times: Vec::new(),
        pk_only_covariates: Vec::new(),
        reset_times: Vec::new(),
        reset_covariates: Vec::new(),
        cens: vec![0, 0, 0],
        occasions: vec![1, 1, 1],
        obs_l2: Vec::new(),
        dose_occasions: vec![1],
        reset_occasions: Vec::new(),
        fremtype: Vec::new(),
        obs_records: vec![],
    };
    (model, subject)
}

/// A `FitResult` with every field at its zero / empty value.
///
/// Four separate test modules had each grown their own ~90-line literal, so a
/// new field meant four edits and a test that only cares about `theta` still
/// had to spell out `sir_resamples_packed`. Build on top of this with struct
/// update syntax instead:
///
/// ```ignore
/// FitResult { theta: vec![1.0], theta_names: vec!["CL".into()], ..empty_fit_result() }
/// ```
pub(crate) fn empty_fit_result() -> FitResult {
    FitResult {
        covariate_relations: Vec::new(),
        restored_from_checkpoint: false,
        method: EstimationMethod::FoceI,
        method_chain: vec![EstimationMethod::FoceI],
        method_wall_times_secs: Vec::new(),
        covariance_wall_time_secs: 0.0,
        converged: false,
        ofv: 0.0,
        aic: 0.0,
        bic: 0.0,
        theta: Vec::new(),
        theta_names: Vec::new(),
        eta_names: Vec::new(),
        omega: nalgebra::DMatrix::zeros(0, 0),
        sigma: Vec::new(),
        sigma_names: Vec::new(),
        residual_correlations: Vec::new(),
        residual_correlation_fixed: Vec::new(),
        error_model: ErrorModel::Proportional,
        covariance_matrix: None,
        se_theta: None,
        se_omega: None,
        se_sigma: None,
        se_residual_correlations: None,
        theta_fixed: Vec::new(),
        omega_fixed: Vec::new(),
        sigma_fixed: Vec::new(),
        omega_init_as_sd: Vec::new(),
        sigma_init_as_sd: Vec::new(),
        subjects: Vec::new(),
        n_obs: 0,
        n_subjects: 0,
        n_parameters: 0,
        n_iterations: 0,
        interaction: false,
        warnings: Vec::new(),
        warnings_structured: Vec::new(),
        sir_ci_theta: None,
        sir_ci_omega: None,
        sir_ci_sigma: None,
        sir_ess: None,
        sir_resamples_packed: None,
        importance_sampling: None,
        impmap_trace: None,
        bayes: None,
        vi: None,
        omega_iov: None,
        kappa_names: Vec::new(),
        kappa_fixed: Vec::new(),
        kappa_init_as_sd: Vec::new(),
        kappa_weights: Vec::new(),
        kappa_weight_typical: Vec::new(),
        se_kappa: None,
        shrinkage_kappa: Vec::new(),
        shrinkage_kappa_by_occ: Vec::new(),
        ebe_kappas: Vec::new(),
        saem_mu_ref_m_step_evals_saved: None,
        saem_n_subjects_hmc: None,
        gradient_method_inner: String::new(),
        gradient_method_outer: String::new(),
        uses_ode_solver: false,
        uses_sde: false,
        n_threads_used: 1,
        nlopt_missing_algorithms: Vec::new(),
        covariance_n_evals_estimated: None,
        trace_path: None,
        ebe_convergence_warnings: 0,
        max_unconverged_subjects: 0,
        total_ebe_fallbacks: 0,
        covariance_status: CovarianceStatus::NotRequested,
        shrinkage_eta: Vec::new(),
        cond_dist: None,
        shrinkage_eps: f64::NAN,
        iwres_lag1_r: f64::NAN,
        dw_statistic: f64::NAN,
        wall_time_secs: 0.0,
        model_name: String::new(),
        ferx_version: String::new(),
        environment: crate::environment::detect(),
        eta_param_info: Vec::new(),
        theta_transform: Vec::new(),
        sigma_types: Vec::new(),
        cov_eigenvalues: None,
        cov_condition_number: None,
        eta_log_transformed: Vec::new(),
        omega_param_corr: None,
        omega_iov_param_corr: None,
        model_path: None,
        data_path: None,
        model_hash: None,
        data_hash: None,
        model_text: None,
        theta_init: Vec::new(),
        omega_init: nalgebra::DMatrix::zeros(0, 0),
        sigma_init: Vec::new(),
        obs_time_range: None,
        final_gradient: None,
        optimizer: String::new(),
        n_starts: 1,
        multi_start_seed: None,
        saem_seed: None,
        sir_seed: None,
        imp_seed: None,
        npde_seed: None,
        bloq_method: String::new(),
        outer_maxiter: 0,
        outer_gtol: 0.0,
        inits_from_nca: None,
        covariate_names: Vec::new(),
        input_columns: Vec::new(),
        #[cfg(feature = "nn")]
        neural_networks: Vec::new(),
        covariate_table: None,
        exclusions: None,
        packed_estimate: None,
        bic_inputs: BicInputs::default(),
        left_init: None,
    }
}

/// A fully-populated, small `FitResult` (3 θ, diagonal 2×2 Ω, one proportional
/// σ, a 3×3 identity covariance, two subjects) for tests that need a real
/// result without running a fit. Shared by the `.fitrx` round-trip tests and
/// the model-selection tests; mutate the fields a case needs.
pub(crate) fn minimal_fit_result() -> FitResult {
    let n_eta = 2;
    FitResult {
        residual_correlation_fixed: Vec::new(),
        se_residual_correlations: None,
        covariate_relations: Vec::new(),
        restored_from_checkpoint: false,
        method: EstimationMethod::FoceI,
        method_chain: vec![EstimationMethod::FoceI],
        method_wall_times_secs: vec![1.234],
        covariance_wall_time_secs: 0.0,
        converged: true,
        ofv: 100.0,
        aic: 110.0,
        bic: 115.0,
        theta: vec![1.0, 2.0, 0.5],
        theta_names: vec!["CL".into(), "V".into(), "KA".into()],
        eta_names: vec!["eta_CL".into(), "eta_V".into()],
        omega: DMatrix::from_row_slice(2, 2, &[0.1, 0.0, 0.0, 0.2]),
        sigma: vec![0.05],
        sigma_names: vec!["prop".into()],
        residual_correlations: Vec::new(),
        error_model: ErrorModel::Proportional,
        covariance_matrix: Some(DMatrix::<f64>::identity(3, 3)),
        se_theta: Some(vec![0.01, 0.02, 0.005]),
        se_omega: Some(vec![0.01, 0.02]),
        se_sigma: Some(vec![0.001]),
        theta_fixed: vec![false, false, false],
        omega_fixed: vec![false, false],
        sigma_fixed: vec![false],
        omega_init_as_sd: vec![false, false],
        sigma_init_as_sd: vec![false],
        subjects: vec![dummy_subject("S1", n_eta, 3), dummy_subject("S2", n_eta, 2)],
        n_obs: 5,
        n_subjects: 2,
        n_parameters: 6,
        n_iterations: 10,
        interaction: true,
        warnings: vec!["watch out".into()],
        warnings_structured: vec![crate::types::classify_warning("watch out")],
        sir_ci_theta: None,
        sir_ci_omega: None,
        sir_ci_sigma: None,
        sir_ess: None,
        sir_resamples_packed: None,
        importance_sampling: None,
        impmap_trace: None,
        bayes: None,
        vi: None,
        omega_iov: None,
        kappa_names: vec![],
        kappa_fixed: vec![],
        kappa_init_as_sd: vec![],
        kappa_weights: Vec::new(),
        kappa_weight_typical: Vec::new(),
        se_kappa: None,
        shrinkage_kappa: vec![],
        shrinkage_kappa_by_occ: vec![],
        ebe_kappas: vec![],
        saem_mu_ref_m_step_evals_saved: None,
        saem_n_subjects_hmc: None,
        gradient_method_inner: "analytic (Dual2)".into(),
        gradient_method_outer: "finite differences".into(),
        uses_ode_solver: false,
        uses_sde: false,
        n_threads_used: 4,
        nlopt_missing_algorithms: vec![],
        covariance_n_evals_estimated: None,
        trace_path: None,
        ebe_convergence_warnings: 0,
        max_unconverged_subjects: 0,
        total_ebe_fallbacks: 0,
        covariance_status: CovarianceStatus::Computed,
        shrinkage_eta: vec![0.1, 0.15],
        cond_dist: None,
        shrinkage_eps: 0.05,
        iwres_lag1_r: 0.12,
        dw_statistic: 1.75,
        wall_time_secs: 1.234,
        model_name: "test_model".into(),
        ferx_version: "0.1.0".into(),
        environment: crate::environment::detect(),
        eta_param_info: vec![
            EtaParamInfo {
                eta_name: "eta_CL".into(),
                param_type: EtaParamType::LogNormal,
                linked_theta: Some("CL".into()),
                individual_param_name: "CL".into(),
            },
            EtaParamInfo {
                eta_name: "eta_V".into(),
                param_type: EtaParamType::LogNormal,
                linked_theta: Some("V".into()),
                individual_param_name: "V".into(),
            },
        ],
        theta_transform: vec![
            ThetaTransform::Log,
            ThetaTransform::Log,
            ThetaTransform::Log,
        ],
        sigma_types: vec![SigmaType::Proportional],
        cov_eigenvalues: Some(vec![1.0, 0.5, 0.2]),
        cov_condition_number: Some(5.0),
        bic_inputs: BicInputs::default(),
        eta_log_transformed: vec![true, true],
        omega_param_corr: None,
        omega_iov_param_corr: None,
        model_path: None,
        data_path: None,
        model_hash: None,
        data_hash: None,
        model_text: None,
        theta_init: vec![1.0, 2.0, 0.5],
        omega_init: DMatrix::from_row_slice(2, 2, &[0.1, 0.0, 0.0, 0.2]),
        sigma_init: vec![0.05],
        obs_time_range: Some((0.25, 24.0)),
        final_gradient: None,
        optimizer: "slsqp".to_string(),
        n_starts: 1,
        multi_start_seed: None,
        saem_seed: None,
        sir_seed: None,
        imp_seed: None,
        npde_seed: None,
        bloq_method: "drop".to_string(),
        outer_maxiter: 300,
        outer_gtol: 1e-4,
        inits_from_nca: None,
        covariate_names: vec!["WT".into(), "AGE".into()],
        input_columns: vec![],
        #[cfg(feature = "nn")]
        neural_networks: Vec::new(),
        covariate_table: None,
        exclusions: None,
        packed_estimate: None,
        left_init: None,
    }
}

/// A `SubjectResult` with deterministic filler diagnostics, for result fixtures.
pub(crate) fn dummy_subject(id: &str, n_eta: usize, n_obs: usize) -> SubjectResult {
    SubjectResult {
        id: id.into(),
        eta: DVector::from_vec((0..n_eta).map(|k| 0.1 * (k as f64 + 1.0)).collect()),
        ipred: (0..n_obs).map(|j| 1.0 + j as f64).collect(),
        pred: (0..n_obs).map(|j| 1.5 + j as f64).collect(),
        iwres: (0..n_obs).map(|j| 0.01 * j as f64).collect(),
        cwres: (0..n_obs).map(|j| -0.02 * j as f64).collect(),
        npde: vec![],
        npd: vec![],
        ofv_contribution: 12.34,
        cens: vec![0; n_obs],
        n_obs,
        pmix: None,
        mixest: None,
        extra_columns: vec![],
        per_obs_tad: vec![],
        compartment_states: vec![],
        #[cfg(feature = "survival")]
        discrete_rows: Vec::new(),
    }
}
